version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest

    steps:
      - checkout

      # Build your project here
      - run:
          name: Build Project
          command: npm install && npm run build

      # Install lftp
      - run:
          name: Install lftp
          command: sudo apt-get update && sudo apt-get install lftp -y

      # Execute the deployment script
      - run:
          name: Deploy to cPanel
          command: bash .circleci/deploy.sh
