name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build

      - name: Deploy to cPanel
        run: |
          # FTP deployment using curl
         curl -T ./dist/ta-meri/* -u ${{ secrets.CPANEL_USERNAME }}:${{ secrets.CPANEL_PASSWORD }} ftp://${{ secrets.CPANEL_HOST }}/ta-meri.com/

